# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ab9c9df65aa3daf4ea488cdcda931f958f988a4ef3ae052580078fc26a975df3866398b7a415125f75bef952d55dffdcd89e5a95417941c254beeea06949fe4

test:
  secret_key_base: fb44aeb8b439db15a1002ca500e7de354165b50b4dd271548fde5209d48e68c20c2eb1b2023e3a80fe19912ab8c49f5c413585e7a67234934af4cf4cc8cd5200

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
